### ISSUE TITLE
Wo stellt denn der BDEW die XML-Formate bereit?

### ISSUE THREAD

**Issue by Safadurimo** [Hochfrequenz/xml-fundamend-python#23]
Hallo,
könnt ihr einmal die Referenz zu der Veröffentlichung bereitstellen? Werden die XML auch auf edi@energy veröffentlicht?

**Comment by hf-kklein** [comment]
Hey @Safadurimo, die Beispiel-Dokumente für UTITLS in
https://github.com/Hochfrequenz/xml-fundamend-python/tree/main/unittests/example_files

, die wir hier für die Unittests verwenden, waren ne zeitlang öffentlich verfügbar (unter dem Stand heute toten Link in der README). Mittlerweile sind die Dokumente hinter einer Paywall aka "BDEW Plus".

Das Problem ist, dass man BDEW-Mitglied sein muss, um da ranzukommen. Das ist bspw. auch für uns als Dienstleister, die wir selbst keine BDEW-Mitglieder sind, etwas hinderlich.

Ich persönlich finde es auch befremdlich, dass man Geld für einen Standard verlangt, den am Ende alle benutzen müssen. Aber daran können wir wohl nichts ändern.

tldr: Die Library hier setzt voraus, dass man selbst Zugang zu den XMLs hat bzw. BDEW Plus-Mitglied ist.

**Comment by Safadurimo** [comment]
Vielen Dank, das ist zwar schade, aber meine Antwort ist komplett beantwortet. Issue kann gerne geschlossen werden.
